version: '3.4'

services:
  redis:
    image: redis
    container_name: demo-shop-redis
    ports:
      - "9379:6379"
    volumes:
      - /home/demo-shop/redis/data:/data
    restart: always
    networks:
      - demo-shop-net
    command: redis-server --appendonly yes --requirepass qGmNTfPtbQYMX6Qz

networks:
  demo-shop-net:
    external: true